### ISSUE TITLE
JbootHttpSessionWapper的问题

### ISSUE THREAD

**Issue by rancedxk** [yangfuhai/jboot#18]
海哥你好，最近在研究jboot的共享session的实现，发现了以下两个问题：
1.类名中Wapper是不是应改为Wrapper，包装意思？

2.该类的getOrCreatSessionId方法第一行代码`String sessionid = ("JSESSIONID");`，想请教这是什么意思，这里是不是应该改为从cookie中取值`String sessionid = getCookie("JSESSIONID");`，要不然所有的sessionid不就“JSESSIONID"？

**Comment by yangfuhai** [comment]
是的，已经更新。https://github.com/yangfuhai/jboot/commit/03d516c36655ac85d2902d24d5cfd8e6a83d2f4b

**Comment by rancedxk** [comment]
基于改过后的代码写了个小测试，代码如下：
`public void sessionTest(){`
`HttpSession session = getSession();`
`Ret ret = Ret.create("sessionid",session.getId());`
`if(getSessionAttr("data")!=null){`
`ret.set("data", getSessionAttr("data"));`
`}else{`
`long data = System.currentTimeMillis();`
`setSessionAttr("data", data);`
`System.out.println(getSessionAttr("data").toString());`
`ret.set("data", data);`
`}`
`renderJson(ret);`
`}`
用FF隐私浏览窗口首次访问时会在第9行抛出空指针异常，简单跟踪进去发现首次访问，用到`session.getId()`，`setSessionAttr`，`getSessionAttr`这几个方法时，都会访问JbootHttpSessionWapper的getOrCreatSessionId方法，但都得不到JSESSIONID值，都会重新生成一次。
这个问题麻烦确认一下。
