### ISSUE TITLE
能否实现spring @RequestBody获取json数据的特性

### ISSUE THREAD

**Issue by jimchou800** [yangfuhai/jboot#47]
JbootController 的getBean 和getModel 以及 @Para ，只能获取表单提交的参数吗？
如果想做到spring 的@RequestBody那样获取Content-Type:application/json 的JSON数据，怎么做？

测试过getBean，getModel，@Para 都拿不到

**Comment by yangfuhai** [comment]
用 getBodyString() 这个方法。
