### ISSUE TITLE
Jboot 使用 metric 报404错误

### ISSUE THREAD

**Issue by jimchou800** [yangfuhai/jboot#54]
1、jboot版本1.4.8

2、配置：

jboot.metric.url=/metrics

jboot.metric.reporter=slf4j

3、在Controller上写@EnableMetricCounter @EnableMetricConcurrency 等统计注解

4、访问 http://127.0.0.1:8080/metrics 报错 404

海哥，请教哪里的问题

**Comment by yangfuhai** [comment]
已经修复。
